openapi: 3.0.3
info:
  title: Материалы
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Dev Server
tags:
  - name: M
    description: Materials

paths:
  /v1/materials:
    get:
      summary: Метод получения списка материалов
      description: Метод предназначен для получения списка всех материалов, сохраненных в БД
      operationId: getMaterials
      tags:
        - M

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен список материалов
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Material"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    post:
      summary: Метод добавления нового материала
      description: Метод предназначен для создания материала в БД
      operationId: createMaterial
      tags:
        - M

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/Material"

      responses:
        "201":
          description: Материал успешно создан
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/CreateEntityResult"
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

  /v1/materials/{materialId}:
    get:
      summary: Метод получения материала по его идентификатору
      description: Метод предназначен для получения данных материала из БД
      operationId: getMaterial
      tags:
        - M

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: materialId
          in: path
          required: true
          description: Идентификатор материала
          schema:
            type: integer
          example: 1000
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен материал
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/Material"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "404":
          $ref: "#/components/responses/Error404Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    put:
      summary: Метод обновления материала
      description: Метод предназначен для обновления материала в БД
      operationId: updateMaterial
      tags:
        - M

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: materialId
          in: path
          required: true
          description: Идентификатор материала
          schema:
            type: integer
          example: 1000

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/Material"

      responses:
        "204":
          description: Материал успешно создан
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    delete:
      summary: Метод удаления материала по его идентификатору
      description: Метод предназначен для удаления данных о материале в БД
      operationId: deleteMaterial
      tags:
        - M

      security:
        - bearerAuth: []

      parameters:
        - name: materialId
          in: path
          required: true
          description: Идентификатор материала
          schema:
            type: integer
          example: 1000

      responses:
        "204":
          description: Материал был удалён

components:

  parameters:
    corellationId: # RFC-6648
      name: CorellationId
      in: header
      schema:
        type: string
      example: "02fa8b1f-672503f2-5add1be1-90ab5d42"

    attrs:
      description: Список атрибутов, которые необходимо вернуть
      name: attrs
      in: query
      schema:
        type: array
        items:
          type: string
      example: [attributeName1, attributeName2]

  schemas:
    AppError:
      type: object
      required:
        - title
        - detail
        - request
        - time
        - errorTraceId
      properties:
        title:
          description: Краткое описание проблемы, понятное человеку
          type: string
          example: "Entity not found"
        detail:
          description: Описание конкретно возникшей ошибки, понятное человеку
          type: string
          example: "Entity [User] with id = [123456] not found. You MUST use PUT to add entity instead of GET"
        request:
          description: Метод и URL запроса
          type: string
          example: "PUT /users/123456"
        time:
          description: Время возникновения ошибки с точностью до миллисекунд
          type: string
          example: "2023-01-01T10:25:37.43+01"
        errorTraceId:
          description: Идентификатор конкретного возникновения ошибки
          type: string
          example: "5add1be1-90ab5d42-02fa8b1f-672503f2"

    AppErrorAttribute:
      type: object
      required:
        - id
        - value
      properties:
        id:
          description: Название атрибута, где произошла ошибка
          type: string
          example: "attributeName"
        value:
          description: Описание ошибки
          type: string
          example: "Атрибут не может быть пустым. Указано недопустимое значение атрибута"

    CreateEntityResult:
      type: object
      required:
        - id
      properties:
        id:
          description: Идентификатор созданного ресурса
          type: integer
          example: 1000

    Material:
      type: object
      description: |-
        Шаблон пользовательского компонента. \
        Спецификация https://printrobot.atlassian.net/wiki/spaces/prdsh/pages/54919268
      properties:
        materialId: # get, store
          type: integer
          example: 3
        materialTypeId: # get, create
          type: integer
          example: 13
        categoryId: # get, create, store
          type: integer
          example: 28
        materialArticle: # get, create, store
          description: "Артикул материала"
          type: string
          example: "мел-170гл_70х100"
        materialName: # get, create, store
          description: "Торговая марка материала" 
          type: string
          example: "Стандартная" 
        materialDescript: # get, create, store
          description: "Описание"
          type: string
          example: "для цифровой печати" 
        materialPrice: # get, create, store
          description: |-
          type: number
          example: 10.12 
        datePriceChanged: # get, create, store
          description: |-
          type: integer
          example: "2020-03-17" 
        quantityMin: # get, create, store
          description: "необходимо иметь мин кол-во на складе"
          type: integer
          example: 500 
        inUsingCalc: # get, create, store
          description: |-
          type: boolean
          example: true  
        isEnabled: # get, create, store
          description: |-
          type: boolean
          example: true
        controlId: # get, create, store
          description: |-
          type: integer
          example: 1202684          
        createdAt:
          description: Дата и время сохранения
          type: string
          example: "2023-01-01T10:25:37+01"

  responses:
    Error400Response:
      description: Некорректные входные данные. Возвращается список атрибутов с ошибками
      content:
        application/json;charset=UTF-8:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/AppErrorAttribute"

    Error401Response:
      description: Пользователь не был аутентифицирован
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error403Response:
      description: Пользователю с текущими правами доступ отклонён
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error404Response:
      description: Запрашиваемый ресурт не был найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error5XXResponse:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT