openapi: 3.0.3
info:
  title: Рассчитанные заказы
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Dev Server
tags:
  - name: O
    description: Рассчитанные заказы

paths:
  /v1/orders:
    get:
      summary: Рассчитанные заказы
      description: Метод предназначен для получения рассчитанных заказов, сохраненного в БД
      operationId: getOrders
      tags:
        - O

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен список заказов
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    post:
      summary: Метод добавления нового заказа
      description: Метод предназначен для создания заказа в БД
      operationId: createOrder
      tags:
        - O

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/Order"

      responses:
        "201":
          description: Успешно создан заказ
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/CreateEntityResult"
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

  /v1/orders/{orderId}:
    get:
      summary: Метод получения заказа по его идентификатору
      description: Метод предназначен для получения данных заказа из БД
      operationId: getOrder
      tags:
        - O

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: orderId
          in: path
          required: true
          description: Идентификатор заказа
          schema:
            type: integer
          example: 1000
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Были получены заказы
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/Order"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "404":
          $ref: "#/components/responses/Error404Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    put:
      summary: Метод обновления заказа
      description: Метод предназначен для обновления заказа в БД
      operationId: updateOrder
      tags:
        - O

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: orderId
          in: path
          required: true
          description: Идентификатор заказа
          schema:
            type: integer
          example: 1000

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/Order"

      responses:
        "204":
          description: Успешно создан заказ
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    delete:
      summary: Метод удаления заказом по идентификатору
      description: Метод предназначен для удаления заказа в БД
      operationId: deleteOrder
      tags:
        - O

      security:
        - bearerAuth: []

      parameters:
        - name: orderId
          in: path
          required: true
          description: Идентификатор заказа
          schema:
            type: integer
          example: 1000

      responses:
        "204":
          description: заказ был удален

components:

  parameters:
    corellationId: # RFC-6648
      name: CorellationId
      in: header
      schema:
        type: string
      example: "02fa8b1f-672503f2-5add1be1-90ab5d42"

    attrs:
      description: Список атрибутов, которые необходимо вернуть
      name: attrs
      in: query
      schema:
        type: array
        items:
          type: string
      example: [attributeName1, attributeName2]

  schemas:
    AppError:
      type: object
      required:
        - title
        - detail
        - request
        - time
        - errorTraceId
      properties:
        title:
          description: Краткое описание проблемы, понятное человеку
          type: string
          example: "Entity not found"
        detail:
          description: Описание конкретно возникшей ошибки, понятное человеку
          type: string
          example: "Entity [User] with id = [123456] not found. You MUST use PUT to add entity instead of GET"
        request:
          description: Метод и URL запроса
          type: string
          example: "PUT /users/123456"
        time:
          description: Время возникновения ошибки с точностью до миллисекунд
          type: string
          example: "2023-01-01T10:25:37.43+01"
        errorTraceId:
          description: Идентификатор конкретного возникновения ошибки
          type: string
          example: "5add1be1-90ab5d42-02fa8b1f-672503f2"

    AppErrorAttribute:
      type: object
      required:
        - id
        - value
      properties:
        id:
          description: Название атрибута, где произошла ошибка
          type: string
          example: "attributeName"
        value:
          description: Описание ошибки
          type: string
          example: "Атрибут не может быть пустым. Указано недопустимое значение атрибута"

    CreateEntityResult:
      type: object
      required:
        - id
      properties:
        id:
          description: Идентификатор созданного ресурса
          type: integer
          example: 1000

    Order:
      type: object
      description: Рассчитанные заказы. Спецификация https://printrobot.atlassian.net/wiki/spaces/prdsh/pages/54919268
      properties:
        orderId: # get, store
          type: integer
          example: 4
        processId: # get, store
          type: integer
          example: 3
        productionId: # get, store
          type: integer
          example: 1
        formatWidth: # get, store
          type: integer
          example: 10
        formatHeight: # get, store
          type: string
          example: Подготовка бумаги
        companyId: # get, store
          type: integer
          example: 27
        customerId: # get, store
          type: integer
          example: 1
        orderCirculation: # get, store
          type: integer
          description: 
          example: 3
        datetimeToWork: # get, store
          type: string
          description: 
          example: 2006-04-04 12:44:00
        isClosedDocs: # get, store
          type: boolean
          example: true
        isUploadedLayouts: # get, store
          type: boolean
          example: normal
        dateClosedDocs: # get, store
          type: string
          description: 
          example: 2006-04-04 12:44:00
        paymentType: # get, store
          type: string
          enum:
            - cash
            - cash_doc
            - cashless
          description: 
          example: last
        agentPayoff: # get, store
          type: boolean
          example: false   
        cashlessShare: # get, store
          type: number
          example: 126.35
        orderPrice: # get, store
          type: number
          example: 456.12 
        orderRuntime: # get, store
          type: integer
          example: 1000
        calculatedOrderPrice: # get, store
          type: number
          example: 223.12
        dateClosed: # get, store
          type: string
          description: 
          example: 2006-04-04 12:44:00          
        systemId: # get, store
          type: integer
          example: 0

  responses:
    Error400Response:
      description: Некорректные входные данные. Возвращается список атрибутов с ошибками
      content:
        application/json;charset=UTF-8:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/AppErrorAttribute"

    Error401Response:
      description: Пользователь не был аутентифицирован
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error403Response:
      description: Пользователю с текущими правами доступ отклонён
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error404Response:
      description: Запрашиваемый ресурт не был найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error5XXResponse:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT