openapi: 3.0.3
info:
  title: Типы процессов
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Dev Server
tags:
  - name: PRCS
    description: Типы процессов

paths:
  /v1/process-types:
    get:
      summary: Метод получения типов процессов
      description: Метод предназначен для получения списка всех типов процессов, сохраненных в БД
      operationId: getProcessTypes
      tags:
        - PRCS

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен список типов процессов
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProcessType"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    post:
      summary: Метод добавления нового типа процесса
      description: Метод предназначен для создания типа процесса в БД
      operationId: createProcessType
      tags:
        - PRCS

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/ProcessType"

      responses:
        "201":
          description: Тип процесса успешно создан
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/CreateEntityResult"
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

  /v1/process-types/{processTypeId}:
    get:
      summary: Метод получения типа процесса по его идентификатору
      description: Метод предназначен для получения данных типа процесса из БД
      operationId: getProcessType
      tags:
        - PRCS

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: processTypeId
          in: path
          required: true
          description: Идентификатор типа процесса
          schema:
            type: integer
          example: 1000
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен тип процесса
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/ProcessType"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "404":
          $ref: "#/components/responses/Error404Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    put:
      summary: Метод обновления типа процесса
      description: Метод предназначен для обновления типа процесса в БД
      operationId: updateProcessType
      tags:
        - PRCS

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: processTypeId
          in: path
          required: true
          description: Идентификатор типа процесса
          schema:
            type: integer
          example: 1000

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/ProcessType"

      responses:
        "204":
          description: Тип процесса успешно создан
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    delete:
      summary: Метод удаления типа процесса по его идентификатору
      description: Метод предназначен для удаления данных о типе процесса в БД
      operationId: deleteProcessType
      tags:
        - PRCS

      security:
        - bearerAuth: []

      parameters:
        - name: processTypeId
          in: path
          required: true
          description: Идентификатор типа процесса
          schema:
            type: integer
          example: 1000

      responses:
        "204":
          description: Тип процесса был удалён

components:

  parameters:
    corellationId: # RFC-6648
      name: CorellationId
      in: header
      schema:
        type: string
      example: "02fa8b1f-672503f2-5add1be1-90ab5d42"

    attrs:
      description: Список атрибутов, которые необходимо вернуть
      name: attrs
      in: query
      schema:
        type: array
        items:
          type: string
      example: [attributeName1, attributeName2]

  schemas:
    AppError:
      type: object
      required:
        - title
        - detail
        - request
        - time
        - errorTraceId
      properties:
        title:
          description: Краткое описание проблемы, понятное человеку
          type: string
          example: "Entity not found"
        detail:
          description: Описание конкретно возникшей ошибки, понятное человеку
          type: string
          example: "Entity [User] with id = [123456] not found. You MUST use PUT to add entity instead of GET"
        request:
          description: Метод и URL запроса
          type: string
          example: "PUT /users/123456"
        time:
          description: Время возникновения ошибки с точностью до миллисекунд
          type: string
          example: "2023-01-01T10:25:37.43+01"
        errorTraceId:
          description: Идентификатор конкретного возникновения ошибки
          type: string
          example: "5add1be1-90ab5d42-02fa8b1f-672503f2"

    AppErrorAttribute:
      type: object
      required:
        - id
        - value
      properties:
        id:
          description: Название атрибута, где произошла ошибка
          type: string
          example: "attributeName"
        value:
          description: Описание ошибки
          type: string
          example: "Атрибут не может быть пустым. Указано недопустимое значение атрибута"

    CreateEntityResult:
      type: object
      required:
        - id
      properties:
        id:
          description: Идентификатор созданного ресурса
          type: integer
          example: 1000

    ProcessType:
      type: object
      description: |-
        Название цветов при печати. \
        Спецификация https://printrobot.atlassian.net/wiki/spaces/prdsh/pages/54919268
      properties:
        processTypeId: # get, store
          type: integer
          example: 2
        parentId: # get, store
          type: integer
          example: 57
        processName: # get, store
          type: string
          example: "Ламинация"
        processClass: # get, store
          type: string
          example: "formula_orders_objects_ProcessLamination"
        processUniqueness: # get, store
          type: string
          example: "work"
        statusExtId: # get, create
          type: integer
          example: 5
        templateShow: # get, create, store
          description: "Шаблон представления" 
          type: string
          example: "_laminationShow.tpl" 
        isContainer: # get, create, store
          description: "???" 
          type: boolean
          example: false
        isCategory: # get, create, store
          type: boolean
          example: false          
        isMaterials: # get, create, store
          description: "???" 
          type: boolean
          example: false
        isMachines: # get, create, store
          description: "???" 
          type: boolean
          example: false  
        isHidden: # get, create, store
          description: "???" 
          type: boolean
          example: false  
        isComplate: # get, create, store
          description: "???" 
          type: boolean
          example: false  
        isManage: # get, create, store
          description: "???" 
          type: boolean
          example: false  
        isSystem: # get, create, store
          description: "???" 
          type: boolean
          example: false  
        isEnabled: # get, create, store
          description: "???" 
          type: boolean
          example: false     
        orderField: # get, create, store
          description: "порядок в техкарте по умолчанию" 
          type: integer
          example: 200            
        createdAt:
          description: Дата и время сохранения
          type: string
          example: "2023-01-01T10:25:37+01"

  responses:
    Error400Response:
      description: Некорректные входные данные. Возвращается список атрибутов с ошибками
      content:
        application/json;charset=UTF-8:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/AppErrorAttribute"

    Error401Response:
      description: Пользователь не был аутентифицирован
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error403Response:
      description: Пользователю с текущими правами доступ отклонён
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error404Response:
      description: Запрашиваемый ресурт не был найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error5XXResponse:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT