openapi: 3.0.3
info:
  title: Название цветов при печати
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Dev Server
tags:
  - name: COLOR
    description: Название цветов при печати

paths:
  /v1/colors:
    get:
      summary: Метод получения названия цветов
      description: Метод предназначен для получения списка всех названий цветов, сохраненных в БД
      operationId: getColors
      tags:
        - COLOR

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен список названий цветов
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Color"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    post:
      summary: Метод добавления нового названия цвета
      description: Метод предназначен для создания названия цвета в БД
      operationId: createColor
      tags:
        - COLOR

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/Color"

      responses:
        "201":
          description: Название цвета успешно создано
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/CreateEntityResult"
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

  /v1/colors/{colorId}:
    get:
      summary: Метод получения названия цвета по его идентификатору
      description: Метод предназначен для получения данных названия цвета из БД
      operationId: getColor
      tags:
        - COLOR

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: colorId
          in: path
          required: true
          description: Идентификатор названия цвета
          schema:
            type: integer
          example: 1000
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Было получено название цвета
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/Color"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "404":
          $ref: "#/components/responses/Error404Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    put:
      summary: Метод обновления названия цвета
      description: Метод предназначен для обновления названия цвета в БД
      operationId: updateColor
      tags:
        - COLOR

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: colorId
          in: path
          required: true
          description: Идентификатор названия цвета
          schema:
            type: integer
          example: 1000

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/Color"

      responses:
        "204":
          description: название цвета успешно создано
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    delete:
      summary: Метод удаления названия цвета по его идентификатору
      description: Метод предназначен для удаления данных о названии цвета в БД
      operationId: deleteColor
      tags:
        - COLOR

      security:
        - bearerAuth: []

      parameters:
        - name: colorId
          in: path
          required: true
          description: Идентификатор названия цвета
          schema:
            type: integer
          example: 1000

      responses:
        "204":
          description: названия цвета былр удалёнр

components:

  parameters:
    corellationId: # RFC-6648
      name: CorellationId
      in: header
      schema:
        type: string
      example: "02fa8b1f-672503f2-5add1be1-90ab5d42"

    attrs:
      description: Список атрибутов, которые необходимо вернуть
      name: attrs
      in: query
      schema:
        type: array
        items:
          type: string
      example: [attributeName1, attributeName2]

  schemas:
    AppError:
      type: object
      required:
        - title
        - detail
        - request
        - time
        - errorTraceId
      properties:
        title:
          description: Краткое описание проблемы, понятное человеку
          type: string
          example: "Entity not found"
        detail:
          description: Описание конкретно возникшей ошибки, понятное человеку
          type: string
          example: "Entity [User] with id = [123456] not found. You MUST use PUT to add entity instead of GET"
        request:
          description: Метод и URL запроса
          type: string
          example: "PUT /users/123456"
        time:
          description: Время возникновения ошибки с точностью до миллисекунд
          type: string
          example: "2023-01-01T10:25:37.43+01"
        errorTraceId:
          description: Идентификатор конкретного возникновения ошибки
          type: string
          example: "5add1be1-90ab5d42-02fa8b1f-672503f2"

    AppErrorAttribute:
      type: object
      required:
        - id
        - value
      properties:
        id:
          description: Название атрибута, где произошла ошибка
          type: string
          example: "attributeName"
        value:
          description: Описание ошибки
          type: string
          example: "Атрибут не может быть пустым. Указано недопустимое значение атрибута"

    CreateEntityResult:
      type: object
      required:
        - id
      properties:
        id:
          description: Идентификатор созданного ресурса
          type: integer
          example: 1000

    Color:
      type: object
      description: |-
        Название цветов при печати. \
        Спецификация https://printrobot.atlassian.net/wiki/spaces/prdsh/pages/54919268
      properties:
        colorId: # get, store
          type: integer
          example: 11
        colorShortName: # get, create
          description: "сокращение" 
          type: string
          example: "silver"
        colorName: # get, create, store
          description: "Название цвета" 
          type: string
          example: "Серебро" 
        isSystem: # get, create, store
          description: "???" 
          type: boolean
          example: false
        createdAt:
          description: Дата и время сохранения
          type: string
          example: "2023-01-01T10:25:37+01"

  responses:
    Error400Response:
      description: Некорректные входные данные. Возвращается список атрибутов с ошибками
      content:
        application/json;charset=UTF-8:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/AppErrorAttribute"

    Error401Response:
      description: Пользователь не был аутентифицирован
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error403Response:
      description: Пользователю с текущими правами доступ отклонён
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error404Response:
      description: Запрашиваемый ресурт не был найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error5XXResponse:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT