openapi: 3.0.3
info:
  title: Настройки оборудования
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Dev Server
tags:
  - name: TM
    description: Настройки оборудования

paths:
  /v1/tools-machines:
    get:
      summary: Метод получения оборудования
      description: Метод предназначен для получения списка всеГо оборудования, сохраненного в БД
      operationId: getToolsMachines
      tags:
        - TM

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен список оборудования
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ToolsMachine"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    post:
      summary: Метод добавления нового оборудования
      description: Метод предназначен для создания оборудования в БД
      operationId: createToolsMachine
      tags:
        - TM

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/ToolsMachine"

      responses:
        "201":
          description: Оборудование успешно создано
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/CreateEntityResult"
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

  /v1/tools-machines/{machineId}:
    get:
      summary: Метод получения оборудования по его идентификатору
      description: Метод предназначен для получения данных оборудования из БД
      operationId: getToolsMachine
      tags:
        - TM

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: categoryId
          in: path
          required: true
          description: Идентификатор категории оборудования
          schema:
            type: integer
          example: 1000
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Было получено оборудование
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/ToolsMachine"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "404":
          $ref: "#/components/responses/Error404Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    put:
      summary: Метод обновления оборудования
      description: Метод предназначен для обновления оборудования в БД
      operationId: updateToolsMachine
      tags:
        - TM

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: categoryId
          in: path
          required: true
          description: Идентификатор оборудования
          schema:
            type: integer
          example: 1000

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/ToolsMachine"

      responses:
        "204":
          description: Оборудование успешно создано
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    delete:
      summary: Метод удаления оборудования по его идентификатору
      description: Метод предназначен для удаления данных об оборудовании в БД
      operationId: deleteToolsMachine
      tags:
        - TM

      security:
        - bearerAuth: []

      parameters:
        - name: categoryId
          in: path
          required: true
          description: Идентификатор оборудования
          schema:
            type: integer
          example: 1000

      responses:
        "204":
          description: Оборудование было удалёно

components:

  parameters:
    corellationId: # RFC-6648
      name: CorellationId
      in: header
      schema:
        type: string
      example: "02fa8b1f-672503f2-5add1be1-90ab5d42"

    attrs:
      description: Список атрибутов, которые необходимо вернуть
      name: attrs
      in: query
      schema:
        type: array
        items:
          type: string
      example: [attributeName1, attributeName2]

  schemas:
    AppError:
      type: object
      required:
        - title
        - detail
        - request
        - time
        - errorTraceId
      properties:
        title:
          description: Краткое описание проблемы, понятное человеку
          type: string
          example: "Entity not found"
        detail:
          description: Описание конкретно возникшей ошибки, понятное человеку
          type: string
          example: "Entity [User] with id = [123456] not found. You MUST use PUT to add entity instead of GET"
        request:
          description: Метод и URL запроса
          type: string
          example: "PUT /users/123456"
        time:
          description: Время возникновения ошибки с точностью до миллисекунд
          type: string
          example: "2023-01-01T10:25:37.43+01"
        errorTraceId:
          description: Идентификатор конкретного возникновения ошибки
          type: string
          example: "5add1be1-90ab5d42-02fa8b1f-672503f2"

    AppErrorAttribute:
      type: object
      required:
        - id
        - value
      properties:
        id:
          description: Название атрибута, где произошла ошибка
          type: string
          example: "attributeName"
        value:
          description: Описание ошибки
          type: string
          example: "Атрибут не может быть пустым. Указано недопустимое значение атрибута"

    CreateEntityResult:
      type: object
      required:
        - id
      properties:
        id:
          description: Идентификатор созданного ресурса
          type: integer
          example: 1000

    ToolsMachine:
      type: object
      description: Настройки оборудования. Спецификация https://printrobot.atlassian.net/wiki/spaces/prdsh/pages/54919268
      properties:
        machineId: # get, store
          type: integer
          example: 1
        machineName: # get, store
          type: string
          example: "Speedmaster CD 102-5 + L"
        categoryId: # get, store
          type: integer
          example: 2
        territoryId: # get, store
          type: integer
          example: 33
        dateInstalled: # get, store
          type: string
          example:  "2023-01-01T10:25:37+01"
        inUsingCalc: # get, store
          type: boolean
          example: true
        isEnabled: # get, store
          type: boolean
          example: true 
        processesCount: # get, store
          type: integer
          example: 64847
        processesRunning: # get, store
          type: integer
          example: 4                             
        processesCanceled:
          description: 
          type: integer
          example: 0

  responses:
    Error400Response:
      description: Некорректные входные данные. Возвращается список атрибутов с ошибками
      content:
        application/json;charset=UTF-8:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/AppErrorAttribute"

    Error401Response:
      description: Пользователь не был аутентифицирован
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error403Response:
      description: Пользователю с текущими правами доступ отклонён
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error404Response:
      description: Запрашиваемый ресурт не был найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error5XXResponse:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT