openapi: 3.0.3
info:
  title: Виды продукции
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Dev Server
tags:
  - name: PRDCT
    description: Виды продукции

paths:
  /v1/production-types:
    get:
      summary: Метод получения видов продукции
      description: Метод предназначен для получения списка всех видов продукции, сохраненных в БД
      operationId: getProductionTypes
      tags:
        - PRDCT

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен список видов продукции
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductionType"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    post:
      summary: Метод добавления нового вида продукции
      description: Метод предназначен для создания вида продукции в БД
      operationId: createProductionType
      tags:
        - PRDCT

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/ProductionType"

      responses:
        "201":
          description: Вид продукции успешно создан
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/CreateEntityResult"
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

  /v1/production-types/{productionTypeId}:
    get:
      summary: Метод получения вида продукции по его идентификатору
      description: Метод предназначен для получения данных вида продукции из БД
      operationId: getProductionType
      tags:
        - PRDCT

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: productionTypeId
          in: path
          required: true
          description: Идентификатор вида продукции
          schema:
            type: integer
          example: 1000
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен вид продукции
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/ProductionType"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "404":
          $ref: "#/components/responses/Error404Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    put:
      summary: Метод обновления вида продукции
      description: Метод предназначен для обновления вида продукции в БД
      operationId: updateProductionType
      tags:
        - PRDCT

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: productionTypeId
          in: path
          required: true
          description: Идентификатор вида продукции
          schema:
            type: integer
          example: 1000

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/ProductionType"

      responses:
        "204":
          description: Вид продукции успешно создан
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    delete:
      summary: Метод удаления вида продукции по его идентификатору
      description: Метод предназначен для удаления данных о виде продукции в БД
      operationId: deleteProductionType
      tags:
        - PRDCT

      security:
        - bearerAuth: []

      parameters:
        - name: productionTypeId
          in: path
          required: true
          description: Идентификатор вида продукции
          schema:
            type: integer
          example: 1000

      responses:
        "204":
          description: Вид продукции был удалён

components:

  parameters:
    corellationId: # RFC-6648
      name: CorellationId
      in: header
      schema:
        type: string
      example: "02fa8b1f-672503f2-5add1be1-90ab5d42"

    attrs:
      description: Список атрибутов, которые необходимо вернуть
      name: attrs
      in: query
      schema:
        type: array
        items:
          type: string
      example: [attributeName1, attributeName2]

  schemas:
    AppError:
      type: object
      required:
        - title
        - detail
        - request
        - time
        - errorTraceId
      properties:
        title:
          description: Краткое описание проблемы, понятное человеку
          type: string
          example: "Entity not found"
        detail:
          description: Описание конкретно возникшей ошибки, понятное человеку
          type: string
          example: "Entity [User] with id = [123456] not found. You MUST use PUT to add entity instead of GET"
        request:
          description: Метод и URL запроса
          type: string
          example: "PUT /users/123456"
        time:
          description: Время возникновения ошибки с точностью до миллисекунд
          type: string
          example: "2023-01-01T10:25:37.43+01"
        errorTraceId:
          description: Идентификатор конкретного возникновения ошибки
          type: string
          example: "5add1be1-90ab5d42-02fa8b1f-672503f2"

    AppErrorAttribute:
      type: object
      required:
        - id
        - value
      properties:
        id:
          description: Название атрибута, где произошла ошибка
          type: string
          example: "attributeName"
        value:
          description: Описание ошибки
          type: string
          example: "Атрибут не может быть пустым. Указано недопустимое значение атрибута"

    CreateEntityResult:
      type: object
      required:
        - id
      properties:
        id:
          description: Идентификатор созданного ресурса
          type: integer
          example: 1000

    ProductionType:
      type: object
      description: |-
        Виды продукции. \
        Спецификация https://printrobot.atlassian.net/wiki/spaces/prdsh/pages/54919268
      properties:
        productionTypeId: # get, store
          type: integer
          example: 3
        parentId: # get, store
          type: integer
          example: 26
        productionName: # get, store
          type: string
          example: "Брошюры"
        isBlank: # get, create, store
          description: "???" 
          type: boolean
          example: false
        defaultCirculation: # get, create, store
          description: "тираж по умолчанию"         
          type: integer
          example: "1000"          
        defaultFormatId: # get, create, store
          description: "формат по умолчанию" 
          type: integer
          example: 12
        isDifferentFormat: # get, create, store
          description: "???" 
          type: boolean
          example: false  
        cutDoubleWidth: # get, create, store
          description: "ширина поля на спуске между продукцией" 
          type: integer
          example: 3  
        cutDoubleHeight: # get, create, store
          description: "высота поля на спуске между продукцией"  
          type: integer
          example: 3  
        bleedWidth: # get, create, store
          description: "ширина поля вылета" 
          type: integer
          example: 2  
        bleedHeight: # get, create, store
          description: "высота поля вылета" 
          type: boolean
          example: false  
        isUsingCalc: # get, create, store
          description: "использовать в калькуляторе" 
          type: boolean
          example: true     
        isEnabled: # get, create, store
          description: "использовать в системе" 
          type: boolean
          example: true  
        isRemote: # get, create, store
          description: "???" 
          type: boolean
          example: false  
        orderField: # get, create, store
          description: "порядок в техкарте по умолчанию" 
          type: integer
          example: 5           
        createdAt:
          description: Дата и время сохранения
          type: string
          example: "2023-01-01T10:25:37+01"

  responses:
    Error400Response:
      description: Некорректные входные данные. Возвращается список атрибутов с ошибками
      content:
        application/json;charset=UTF-8:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/AppErrorAttribute"

    Error401Response:
      description: Пользователь не был аутентифицирован
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error403Response:
      description: Пользователю с текущими правами доступ отклонён
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error404Response:
      description: Запрашиваемый ресурт не был найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error5XXResponse:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT