openapi: 3.0.3
info:
  title: Сотрудники компании
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Dev Server
tags:
  - name: EMPEE
    description: Сотрудники компании

paths:
  /v1/employees:
    get:
      summary: Сотрудники компании
      description: Метод предназначен для получения сотрудников, сохраненного в БД
      operationId: getEmployees
      tags:
        - EMPEE

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен список сотрудников
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    post:
      summary: Метод добавления нового сотрудника
      description: Метод предназначен для создания сотрудника в БД
      operationId: createEmployee
      tags:
        - EMPEE

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/Employee"

      responses:
        "201":
          description: Успешно создан сотрудник
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/CreateEntityResult"
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

  /v1/employees/{employeeId}:
    get:
      summary: Метод получения сотрудника по его идентификатору
      description: Метод предназначен для получения данных сотрудника из БД
      operationId: getEmployee
      tags:
        - EMPEE

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: employeeId
          in: path
          required: true
          description: Идентификатор сотрудника
          schema:
            type: integer
          example: 1000
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Были получены сотрудники
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/Employee"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "404":
          $ref: "#/components/responses/Error404Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    put:
      summary: Метод обновления сотрудника
      description: Метод предназначен для обновления сотрудника в БД
      operationId: updateEmployee
      tags:
        - EMPEE

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: employeeId
          in: path
          required: true
          description: Идентификатор сотрудника
          schema:
            type: integer
          example: 1000

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/Employee"

      responses:
        "204":
          description: Успешно создан сотрудник
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    delete:
      summary: Метод удаления сотрудника по идентификатору
      description: Метод предназначен для удаления сотрудника в БД
      operationId: deleteEmployee
      tags:
        - EMPEE

      security:
        - bearerAuth: []

      parameters:
        - name: employeeId
          in: path
          required: true
          description: Идентификатор сотрудника
          schema:
            type: integer
          example: 1000

      responses:
        "204":
          description: сотрудник был удален

components:

  parameters:
    corellationId: # RFC-6648
      name: CorellationId
      in: header
      schema:
        type: string
      example: "02fa8b1f-672503f2-5add1be1-90ab5d42"

    attrs:
      description: Список атрибутов, которые необходимо вернуть
      name: attrs
      in: query
      schema:
        type: array
        items:
          type: string
      example: [attributeName1, attributeName2]

  schemas:
    AppError:
      type: object
      required:
        - title
        - detail
        - request
        - time
        - errorTraceId
      properties:
        title:
          description: Краткое описание проблемы, понятное человеку
          type: string
          example: "Entity not found"
        detail:
          description: Описание конкретно возникшей ошибки, понятное человеку
          type: string
          example: "Entity [User] with id = [123456] not found. You MUST use PUT to add entity instead of GET"
        request:
          description: Метод и URL запроса
          type: string
          example: "PUT /users/123456"
        time:
          description: Время возникновения ошибки с точностью до миллисекунд
          type: string
          example: "2023-01-01T10:25:37.43+01"
        errorTraceId:
          description: Идентификатор конкретного возникновения ошибки
          type: string
          example: "5add1be1-90ab5d42-02fa8b1f-672503f2"

    AppErrorAttribute:
      type: object
      required:
        - id
        - value
      properties:
        id:
          description: Название атрибута, где произошла ошибка
          type: string
          example: "attributeName"
        value:
          description: Описание ошибки
          type: string
          example: "Атрибут не может быть пустым. Указано недопустимое значение атрибута"

    CreateEntityResult:
      type: object
      required:
        - id
      properties:
        id:
          description: Идентификатор созданного ресурса
          type: integer
          example: 1000

    Employee:
      type: object
      description: Рассчитанные заказы. Спецификация https://printrobot.atlassian.net/wiki/spaces/prdsh/pages/54919268
      properties:
        employeeId: # get, store
          type: integer
          example: 4
        employeeAlias: # get, store
          type: string
          example: Svetik
        departmentId: # get, store
          type: integer
          example: 1
        appointmentId: # get, store
          type: integer
          example: 10
        extrachargeGroupId: # get, store
          type: integer
          example: 90
        firmId: # get, store
          type: integer
          example: 2
        employeePhones: # get, store
          type: string
          example: +1 100 20001888
        employeeAppointment: # get, store
          type: string
          description: 
          example: 3
        dateBirthday: # get, store
          type: string
          description: 
          example: 1953-11-25
        dateJobStarted: # get, store
          type: string
          example: 1973-11-25
        dateJobFinished: # get, store
          type: string
          example: 1993-11-25
        employeeInn: # get, store
          type: integer
          description: 
          example: 7790000034234450
        addressId: # get, store
          type: string
          description: 
          example: last
        tnPhotoId: # get, store
          type: integer
          example: false   
        photoId: # get, store
          type: integer
          example: 126
        passportNumber: # get, store
          type: integer
          example: 16 345567
        passportWhoGave: # get, store
          type: string
          example: ОВД
        passportDateGave: # get, store
          type: string
          example: 2006-04-04
        passportAddressId: # get, store
          type: string
          description: 
          example: Москва, ул. Новаторов
        rateOfSalary: # get, store
          type: integer
          example: 123000
        salary: # get, store
          type: number
          example: 22300.12
        advanceMoney: # get, store
          type: string
          description: 
          example: 22300
        lastOrderId: # get, store
          type: integer
          example: 0
        isArchived: # get, store
          type: boolean
          description: 
          example: false
        isDefaultCalc: # get, store
          type: boolean
          example: false

  responses:
    Error400Response:
      description: Некорректные входные данные. Возвращается список атрибутов с ошибками
      content:
        application/json;charset=UTF-8:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/AppErrorAttribute"

    Error401Response:
      description: Пользователь не был аутентифицирован
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error403Response:
      description: Пользователю с текущими правами доступ отклонён
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error404Response:
      description: Запрашиваемый ресурт не был найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error5XXResponse:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT