openapi: 3.0.3
info:
  title: Типы материалов
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Dev Server
tags:
  - name: MT
    description: Materials Types

paths:
  /v1/materials-types:
    get:
      summary: Метод получения списка типов материалов
      description: Метод предназначен для получения списка всех типов материалов, сохраненных в БД
      operationId: getMaterialsTypes
      tags:
        - MT

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен список типов материалов
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MaterialType"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    post:
      summary: Метод добавления нового типа материала
      description: Метод предназначен для создания нового типа материала в БД
      operationId: createMaterialType
      tags:
        - MT

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/MaterialType"

      responses:
        "201":
          description: Тип материала успешно создан
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/CreateEntityResult"
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

  /v1/materials-types/{typeId}:
    get:
      summary: Метод получения типов материалов по его идентификатору
      description: Метод предназначен для получения данных типов материалов из БД
      operationId: getMaterialType
      tags:
        - MT

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: typeId
          in: path
          required: true
          description: Идентификатор типа материала
          schema:
            type: integer
          example: 1000
        - $ref: "#/components/parameters/attrs"

      responses:
        "200":
          description: Был получен типа материала
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/MaterialType"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "404":
          $ref: "#/components/responses/Error404Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    put:
      summary: Метод обновления типа материала
      description: Метод предназначен для обновления типа материала в БД
      operationId: updateMaterialType
      tags:
        - MT

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/corellationId"
        - name: typeId
          in: path
          required: true
          description: Идентификатор типа материала
          schema:
            type: integer
          example: 1000

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/MaterialType"

      responses:
        "204":
          description: Тип материала успешно создан
        "400":
          $ref: "#/components/responses/Error400Response"
        "401":
          $ref: "#/components/responses/Error401Response"
        "403":
          $ref: "#/components/responses/Error403Response"
        "5XX":
          $ref: "#/components/responses/Error5XXResponse"

    delete:
      summary: Метод удаления типа материала по его идентификатору
      description: Метод предназначен для удаления данных о типе материала в БД
      operationId: deleteMaterialType
      tags:
        - MT

      security:
        - bearerAuth: []

      parameters:
        - name: typeId
          in: path
          required: true
          description: Идентификатор типа материала
          schema:
            type: integer
          example: 1000

      responses:
        "204":
          description: Тип материала был удалён

components:

  parameters:
    corellationId: # RFC-6648
      name: CorellationId
      in: header
      schema:
        type: string
      example: "02fa8b1f-672503f2-5add1be1-90ab5d42"

    attrs:
      description: Список атрибутов, которые необходимо вернуть
      name: attrs
      in: query
      schema:
        type: array
        items:
          type: string
      example: [attributeName1, attributeName2]

  schemas:
    AppError:
      type: object
      required:
        - title
        - detail
        - request
        - time
        - errorTraceId
      properties:
        title:
          description: Краткое описание проблемы, понятное человеку
          type: string
          example: "Entity not found"
        detail:
          description: Описание конкретно возникшей ошибки, понятное человеку
          type: string
          example: "Entity [User] with id = [123456] not found. You MUST use PUT to add entity instead of GET"
        request:
          description: Метод и URL запроса
          type: string
          example: "PUT /users/123456"
        time:
          description: Время возникновения ошибки с точностью до миллисекунд
          type: string
          example: "2023-01-01T10:25:37.43+01"
        errorTraceId:
          description: Идентификатор конкретного возникновения ошибки
          type: string
          example: "5add1be1-90ab5d42-02fa8b1f-672503f2"

    AppErrorAttribute:
      type: object
      required:
        - id
        - value
      properties:
        id:
          description: Название атрибута, где произошла ошибка
          type: string
          example: "attributeName"
        value:
          description: Описание ошибки
          type: string
          example: "Атрибут не может быть пустым. Указано недопустимое значение атрибута"

    CreateEntityResult:
      type: object
      required:
        - id
      properties:
        id:
          description: Идентификатор созданного ресурса
          type: integer
          example: 1000

    MaterialType:
      type: object
      description: |-
        Типы материалов. \
        Спецификация https://printrobot.atlassian.net/wiki/spaces/...
      properties:
        materialTypeId: # get, store
          type: integer
          example: 13
        categoryId: # get, create
          type: integer
          example: 26
        materialName: # get, create, store
          type: string
          example: "Бумага"
        measureId: # get, create, store
          description: |-
          type: integer
          example: 1
        isToolSet: # get, create, store
          description: |-
          type: boolean
          example: true
        isFloat: # get, create, store
          description: |-
          type: boolean
          example: true
        isAutoReserving: # get, create, store
          description: Обязательность заполнения поля
          type: boolean
          example: false
        isRecalcKg2sheet: # get, store
          description: |-
          type: boolean
          example: false
        createdAt:
          description: Дата и время типа материала
          type: string
          example: "2023-01-01T10:25:37+01"

  responses:
    Error400Response:
      description: Некорректные входные данные. Возвращается список атрибутов с ошибками
      content:
        application/json;charset=UTF-8:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/AppErrorAttribute"

    Error401Response:
      description: Пользователь не был аутентифицирован
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error403Response:
      description: Пользователю с текущими правами доступ отклонён
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error404Response:
      description: Запрашиваемый ресурт не был найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

    Error5XXResponse:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT