techCard: # настройки спецификации продукции для которой будут происходит расчёты
  source: mrcalc\Production, # название класса продукции
  name: Листовки офсетная печать, # название продукции, которое будет выводиться в сообщениях пользователю

  processes: # список описаний процессов, которые будут использоваться текущей продукцией
    - source: ./processes/PreparingLayout # 01 - Подготовка макета
      name: Подготовка макета1

    - source: ./processes/PaperPreparation # 02 - Подготовка бумаги
      name: Работа
      processes:
        - source: ./processes/CuttingPaperIntoPrintFormat # 03 - Резка большой бумаги в формат для печати
          name: Печать


  // 03 - Резка большой бумаги в формат для печати
  $processCuttingPaperIntoPrintFormat,

  // 04 - Изготовление офсетных форм для печати
  $processOffsetFormsProductionForPrinting,

  // 05 - Офсетная листовая печать
  $processOffsetSheetPrinting,

  // Резка отпечатанных листов, чтоб они по формату прошли в ламинатор. Возможно этот алгоритм в процесс Ламинация включить
  // ...
  // УФ-лак на лист после ламинации. УФ-лак накладывает ограничение на формат листа для печати и для ламинации.
  // ...

  // 06 - Ламинация изделий
  $processLamination,

  // 07 - Навивка на проволку блока изделий
  $processBinding,

  // 08 - Установка ригеля
  // $processInstallingRigel,

  // 09 - Фальцовка изделий
  $processFolding,

  // 10 - Биговка изделий
  $processCreasing,

  // 11 - Лакировка изделий
  $processCoating,

  // 12 - Сверление отверстий в изделиях
  $processDrilling,

  // 13 - Обрезка углов изделий
  $processCroppingCorners,

  // 14 - Резка в готовый формат
  $processCuttingIntoReadyFormat,

  // 15 - Вырубка фигурных изделий из листа
  $processDieCutting,
  )
  );